"""Liquidity-filtered symbol universe: the pinned coins plus every Binance spot USDT pair liquid enough
for the strategy's edge to survive fees and slippage.

`research universe` measures every active pair (average daily quote volume over `lookback_days`, best
bid/ask spread now), keeps the pinned symbols and the hand-written instances whatever their numbers,
adds every other pair that clears `min_volume_usd` and `max_spread_pct`, and rewrites two places in
config/strategies.yaml: the `symbols:` line and the auto-generated instance block between the
UNIVERSE markers. Everything else in the file (comments, hand-written instances) is left untouched.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Protocol

import yaml
from rich.console import Console
from rich.table import Table

from .config import StrategyInstance, UniverseConfig, load_config

console = Console()

BEGIN_MARK = "# --- UNIVERSE: auto-generated by `research universe`, do not edit by hand ---"
END_MARK = "# --- END UNIVERSE ---"
SYMBOLS_RE = re.compile(r"^symbols:\s*\[[^\]]*\]\s*$", re.MULTILINE)
QUOTE = "USDT"


@dataclass
class Candidate:
    symbol: str  # BTCUSDT
    base: str
    avg_volume_usd: float  # mean daily quote volume over the lookback
    spread_pct: float  # (ask - bid) / mid * 100
    history_days: int  # closed daily candles available, counted up to max(lookback_days, min_age_days)


@dataclass
class Selection:
    kept: list[str]  # pinned + hand-written instances, in config order
    added: list[Candidate]  # auto-added, sorted by volume desc
    rejected: list[tuple[Candidate, str]]  # (candidate, reason) for the report


# ---- pure ----------------------------------------------------------------------------------------


def select(kept: list[str], candidates: list[Candidate], u: UniverseConfig) -> Selection:
    """Keep `kept` unconditionally; add candidates that clear every bar, best volume first, up to max_symbols."""
    added: list[Candidate] = []
    rejected: list[tuple[Candidate, str]] = []
    for c in sorted(candidates, key=lambda c: -c.avg_volume_usd):
        if c.symbol in kept:
            continue
        if c.base in u.exclude:
            rejected.append((c, "excluded"))
        elif c.history_days < max(u.lookback_days, u.min_age_days):
            rejected.append((c, f"only {c.history_days}d of history (min {max(u.lookback_days, u.min_age_days)})"))
        elif c.avg_volume_usd < u.min_volume_usd:
            rejected.append((c, f"volume {c.avg_volume_usd / 1e6:.1f}M < {u.min_volume_usd / 1e6:.0f}M"))
        elif c.spread_pct > u.max_spread_pct:
            rejected.append((c, f"spread {c.spread_pct:.3f}% > {u.max_spread_pct}%"))
        elif len(kept) + len(added) >= u.max_symbols:
            rejected.append((c, f"max_symbols {u.max_symbols} reached"))
        else:
            added.append(c)
    return Selection(kept=list(kept), added=added, rejected=rejected)


def instance_id(template: StrategyInstance, symbol: str) -> str:
    base = symbol.removesuffix(QUOTE)
    prefix = template.id.split("_")[0]  # s1 from s1_btc_15m
    return f"{prefix}_{base.lower()}_{template.entry_tf}"


def _flow(d: dict) -> str:
    return yaml.safe_dump(d, default_flow_style=True, width=10_000, sort_keys=False).strip()


def render_instances(template: StrategyInstance, symbols: list[str]) -> str:
    """One copy of the template instance per symbol, in the same flow style as the hand-written blocks."""
    lines: list[str] = []
    for s in symbols:
        lines += [
            f"- id: {instance_id(template, s)}",
            f"  type: {template.type}",
            f"  symbol: {s}",
            f"  entry_tf: {template.entry_tf}",
            f"  regime_tf: {template.regime_tf}",
        ]
        if template.range_tf:
            lines.append(f"  range_tf: {template.range_tf}")
        lines += [
            "  enabled: true",
            f"  params: {_flow(template.params)}",
            f"  exit: {_flow(template.exit.model_dump())}",
        ]
    return "\n".join(lines)


def rewrite_config(text: str, symbols: list[str], instances: str, stamp: str) -> str:
    """Replace the `symbols:` line and the UNIVERSE block; insert the block before `regime:` when absent."""
    if not SYMBOLS_RE.search(text):
        raise ValueError("config has no single-line `symbols: [...]` entry to rewrite")
    text = SYMBOLS_RE.sub(f"symbols: [{', '.join(symbols)}]", text, count=1)
    block = f"{BEGIN_MARK}\n# refreshed {stamp}\n{instances}\n{END_MARK}" if instances else f"{BEGIN_MARK}\n# refreshed {stamp}\n{END_MARK}"
    if BEGIN_MARK in text and END_MARK in text:
        start, end = text.index(BEGIN_MARK), text.index(END_MARK) + len(END_MARK)
        return text[:start] + block + text[end:]
    m = re.search(r"^regime:", text, re.MULTILINE)
    if not m:
        raise ValueError("config has no `regime:` line to insert the UNIVERSE block before")
    return text[: m.start()] + block + "\n" + text[m.start() :]


def hand_written_symbols_from_text(text: str) -> set[str]:
    """Symbols of instances outside the UNIVERSE block (parsed from the raw file so the block is separable)."""
    if BEGIN_MARK in text and END_MARK in text:
        start, end = text.index(BEGIN_MARK), text.index(END_MARK) + len(END_MARK)
        text = text[:start] + text[end:]
    raw = yaml.safe_load(text) or {}
    return {s["symbol"] for s in raw.get("strategies", [])}


# ---- exchange ------------------------------------------------------------------------------------


class Market(Protocol):
    """The slice of ccxt.binance the universe scan uses; tests pass a fake."""

    rateLimit: int

    def load_markets(self) -> dict: ...
    def fetch_tickers(self) -> dict: ...
    def publicGetTickerBookTicker(self) -> list[dict]: ...
    def publicGetKlines(self, params: dict) -> list[list]: ...


def scan(ex: Market, u: UniverseConfig, sleep: bool = True) -> list[Candidate]:
    """Measure every active spot USDT pair. The 24h ticker prefilters (a pair under a quarter of the bar
    today cannot average the bar over the lookback without a collapse), then daily klines give the
    lookback average and the book ticker the spread."""
    markets = ex.load_markets()
    pairs = {k: v for k, v in markets.items() if v.get("spot") and v.get("active") and v.get("quote") == QUOTE}
    tickers = ex.fetch_tickers()
    book = {b["symbol"]: b for b in ex.publicGetTickerBookTicker()}
    out: list[Candidate] = []
    for key, m in pairs.items():
        base = m["base"]
        if base in u.exclude:
            continue
        t = tickers.get(key) or {}
        if (t.get("quoteVolume") or 0) < u.min_volume_usd / 4:
            continue
        symbol = m["id"]
        need = max(u.lookback_days, u.min_age_days)  # enough daily bars to measure both volume and listing age
        kl = ex.publicGetKlines({"symbol": symbol, "interval": "1d", "limit": min(need + 1, 1000)})
        closed = [k for k in kl if int(k[6]) < int(time.time() * 1000)]  # drop the forming day
        recent = closed[-u.lookback_days :]
        avg = sum(float(k[7]) for k in recent) / len(recent) if recent else 0.0
        b = book.get(symbol)
        bid, ask = (float(b["bidPrice"]), float(b["askPrice"])) if b else (0.0, 0.0)
        spread = (ask - bid) / ((ask + bid) / 2) * 100 if bid > 0 and ask > 0 else 999.0
        out.append(Candidate(symbol=symbol, base=base, avg_volume_usd=avg, spread_pct=spread, history_days=len(closed)))
        if sleep:
            time.sleep(ex.rateLimit / 1000)
    return out


def make_market() -> Market:
    import ccxt

    return ccxt.binance({"enableRateLimit": True})


# ---- refresh -------------------------------------------------------------------------------------


@dataclass
class Refresh:
    selection: Selection
    symbols: list[str]  # final symbols line
    new_symbols: list[str]  # auto-added symbols not in the file before
    dropped: list[str]  # previously auto-added symbols that fell below the bar
    text: str  # rewritten config


def refresh(path: Path, ex: Market | None = None, sleep: bool = True) -> Refresh:
    cfg = load_config(path)
    if cfg.universe is None:
        raise ValueError("config has no `universe:` block")
    u = cfg.universe
    text = path.read_text(encoding="utf-8")
    hand = hand_written_symbols_from_text(text)
    kept = [s for s in cfg.symbols if s in u.pinned or s in hand]
    for s in u.pinned:
        if s not in kept:
            kept.append(s)
    candidates = scan(ex or make_market(), u, sleep=sleep)
    sel = select(kept, candidates, u)
    template = next(s for s in cfg.strategies if s.id == u.template)
    added_symbols = [c.symbol for c in sel.added]
    symbols = kept + added_symbols
    instances = render_instances(template, added_symbols)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    new_text = rewrite_config(text, symbols, instances, stamp)
    before_auto = [s for s in cfg.symbols if s not in kept]
    return Refresh(
        selection=sel, symbols=symbols,
        new_symbols=[s for s in added_symbols if s not in cfg.symbols],
        dropped=[s for s in before_auto if s not in added_symbols],
        text=new_text,
    )


def report(r: Refresh, u: UniverseConfig) -> None:
    t = Table(title=f"universe: {len(r.symbols)} symbols (kept {len(r.selection.kept)}, auto {len(r.selection.added)})")
    t.add_column("symbol")
    t.add_column("30d avg volume", justify="right")
    t.add_column("spread", justify="right")
    t.add_column("status")
    for c in r.selection.added:
        t.add_row(c.symbol, f"${c.avg_volume_usd / 1e6:,.1f}M", f"{c.spread_pct:.3f}%", "NEW" if c.symbol in r.new_symbols else "auto")
    console.print(t)
    near = [(c, why) for c, why in r.selection.rejected if c.avg_volume_usd >= u.min_volume_usd / 2 and why != "excluded"]
    if near:
        console.print("[dim]close but rejected:[/] " + ", ".join(f"{c.symbol} ({why})" for c, why in near[:15]))
    if r.dropped:
        console.print(f"[yellow]dropped (fell below the bar):[/] {', '.join(r.dropped)}")
    console.print(f"kept: {', '.join(r.selection.kept)}")
