/**
 * Generates zod schemas from ../schemas/*.json into ../src/gen/.
 * Run: pnpm --filter @trading/contracts gen
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");
const outDir = join(here, "..", "src", "gen");
mkdirSync(outDir, { recursive: true });

const files = readdirSync(schemasDir).filter((f) => f.endsWith(".json")).sort();
const index: string[] = ["// AUTO-GENERATED by scripts/generate.ts — do not edit", ""];

for (const file of files) {
  const schema = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  const name: string = schema.title;
  const code = jsonSchemaToZod(schema, { name: `${name}Schema`, module: "esm", type: name });
  const base = file.replace(/\.json$/, "");
  writeFileSync(join(outDir, `${base}.ts`), `// AUTO-GENERATED from schemas/${file} — do not edit\n${code}`);
  index.push(`export * from "./${base}.js";`);
}
writeFileSync(join(outDir, "index.ts"), index.join("\n") + "\n");
console.log(`generated ${files.length} zod schema(s) -> ${outDir}`);
